Tennis-Competitions.com/Models/ErrorViewModel.cs
namespace Tennis_Competitions.com.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tennis-Competitions.com/Controllers/HomeController.cs
namespace Tennis_Competitions.com.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;
    using Tennis_Competitions.com.Models;

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tennis-Competitions.com/Controllers/MatchController.cs
namespace Tennis_Competitions.com.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Tennis_Competitions.Services.Contracts;

    public class MatchController : Controller
    {
        private readonly IMatchService matchService;

        public MatchController(IMatchService _matchService)
        {
            matchService = _matchService;
        }

        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var match = await matchService.GetMatchById(id);

                return View(match);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Tennis-Competitions.com/Controllers/PlayerController.cs
namespace Tennis_Competitions.com.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Tennis_Competitions.Services.Contracts;

    public class PlayerController : Controller
    {
        private readonly IPlayerService playerService;

        public PlayerController(IPlayerService _playerService)
        {
            playerService = _playerService;
        }

        public async Task<IActionResult> Index()
        {
            var players = await playerService.GetAllPlayers();

            return View(players);
        }

        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var player = await playerService.GetPlayerById(id);

                return View(player);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

        }
    }
}

Tennis-Competitions.com/Controllers/TournamentController.cs
namespace Tennis_Competitions.com.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Tennis_Competitions.Services.Contracts;

    public class TournamentController : Controller
    {
        private readonly ITournamentService tournamentService;

        public TournamentController(ITournamentService _tournamentService)
        {
            tournamentService = _tournamentService;
        }

        public async Task<IActionResult> Index()
        {
            var tours = await tournamentService.GetAllTournaments();

            return View(tours);
        }

        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var tour = await tournamentService.GetTournamentById(id);

                return View(tour);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Tennis-Competitions.com/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Tennis-Competitions.com</h1>
</div>

Tennis-Competitions.com/Views/Match/Details.cshtml
@model MatchServiceModel

<table class="table">
    <thead>
        <tr>
            <th colspan="3" class="textCenter">
                @Model.Name
            </th>
        </tr>
        <tr>
            <th><a asp-area="" asp-controller="Player" asp-action="Details" asp-route-id="@Model.FirstPlayerId" class="playerName">@Model.FirstPlayerName</a></th>
            <th class="textCenter">Players</th>
            <th class="textRight"><a asp-area="" asp-controller="Player" asp-action="Details" asp-route-id="@Model.SecondPlayerId" class="playerName" >@Model.SecondPlayerName</a></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.AcesFirstPlayer</td>
            <th class="textCenter">ACES</th>
            <td class="textRight">@Model.AcesSecondPlayer</td>
        </tr>
        <tr>
            <td>@Model.DoubleFoultsFirstPlayer</td>
            <th class="textCenter">DOUBLE FOULTS</th>
            <td class="textRight">@Model.DoubleFoultsSecondPlayer</td>
        </tr>
        <tr>
            <td>@Model.WinnersFirstPlayer</td>
            <th class="textCenter">WINNERS</th>
            <td class="textRight">@Model.WinnersSecondPlayer</td>
        </tr>
        <tr>
            <td>@Model.UnforcesErrorsFirstPlayer</td>
            <th class="textCenter">UNFORCES ERRORS</th>
            <td class="textRight">@Model.UnforcesErrorsSecondPlayer</td>
        </tr>
    </tbody>
</table>

Tennis-Competitions.com/Views/Player/Details.cshtml
@model PlayerServiceModel

<div class="mb-3" id="playerAvatar">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="@Model.ImageURL" class="img-fluid rounded-start" id="playerPhoto" alt="@Model.LastName">
        </div>
        <div class="col-md-8">
            <div class="container">
                <div class="card-body">
                    <h5 class="card-title">@Model.FirstName @Model.LastName</h5>
                    <div class="row">
                        <table class="table-player-profile table-player-profile3">
                            <tr>
                                <td class="table-player-profile1 table-player-profile3 table-player-border">Wins &nbsp<p id="largetext">@Model.Wins</p></td>
                                <td class="table-player-profile1 table-player-profile4 table-player-border textRight">Lost &nbsp<p id="largetext">@Model.Loses</p></td>
                            </tr>
                            <tr>
                                <td class="table-player-profile2 table-player-profile3 table-player-border">Titles &nbsp<p id="largetext">@Model.TournamentsWins</p> </td>
                                <td class="table-player-profile2 table-player-profile4 table-player-border"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col">
                            Matches &nbsp<p id="largetext">@Model.MatchesCount</p>
                        </div>
                        <div class="col"></div>
                    </div>
                    <div class="row">
                        <div class="col">
                            Tournaments &nbsp<p id="largetext">@Model.TournamentsCount</p>
                        </div>
                        <div class="col"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Tennis-Competitions.com/Views/Player/Index.cshtml
@model ICollection<PlayerServiceModel>

<h1>Players</h1>
<br />

<div class="row row-cols-1 row-cols-md-4 g-4">
    @{
        foreach (var player in Model)
        {
            <div class="col">
                <partial name="_PlayerPartial" model="@player" />
            </div>
        }
    }
</div>

Tennis-Competitions.com/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tennis_Competitions.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/octicons/octicons.css">
    <link rel="stylesheet" href="~/Tennis_Competitions.com.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tennis-Competitions.com</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tournament" asp-action="Index">Tournaments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                    </ul>
                    @*<partial name="_LoginPartial" />*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Tennis_Competitions.com - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tennis-Competitions.com/Views/Shared/_MatchPartial.cshtml
@model MatchServiceModel

<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">@Model.Name</h5>
    <p class="card-text">@Model.FirstPlayerName vs @Model.SecondPlayerName</p>
    <br />
    <a asp-area="" asp-controller="Match" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Open</a>
  </div>
</div>

Tennis-Competitions.com/Views/Shared/_PlayerPartial.cshtml
@model PlayerServiceModel

<div class="playerProfileBody">
    <div id="wrapper">
        <div id="avatar">
            <img src="@Model.ImageURL" alt="@Model.LastName" class="playerImage">
        </div>
        <div class="user-info">
            <div id="main-info">
                <h1> @Model.FirstName<br />@Model.LastName</h1>
                <a asp-area="" asp-controller="player" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-success">See more</a>
            </div>
        </div>
    </div>
</div>

Tennis-Competitions.com/Views/Shared/_TournamentPartial.cshtml
@model TournamentServiceModel

<div class="card" id="tournament-card">
    <img src="@Model.ImageURL" class="tournamentImage" alt="@Model.Name">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">Surface: @Model.Surface.ToString()</p>
        <hr />
        <a asp-area="" asp-controller="Tournament" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Details</a>
    </div>
</div>

Tennis-Competitions.com/Views/Tournament/Details.cshtml
@model TournamentServiceModel

<h2>@Model.Name</h2>
@{
    foreach (var match in Model.Matches)
    {
        <partial name="_MatchPartial" model="@match" />
        <br />
    }
}

Tennis-Competitions.com/Views/Tournament/Index.cshtml
@model IEnumerable<TournamentServiceModel>

<h1>Tournaments</h1>
<br />

<div class="row row-cols-1 row-cols-md-4 g-4">
    @{
        foreach (var tour in Model)
        {
            <div class="col">
                <partial name="_TournamentPartial" model="@tour" />
            </div>
        }
    }
</div>